info:
  name: nood-auth
  author: singh
  description: 认证服务
server:
  port: 8764
  tomcat:
    uri-encoding: UTF-8

logging:
  path: logs
  level:
    root: INFO

# eureka:
#   instance:
#     prefer-ip-address: true
#     ip-address: ${spring.cloud.client.ip-address}:${server.port}
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone : http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://10.10.10.176:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: mr888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.10.10.176
    port: 6379
    timeout: 6000
    database: 4
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    # 输出日志
    show-sql: true
    # 数据库类型
    database: mysql
  consul:
  host: 127.0.0.1
  port: 8500
  discovery:
    register: true
    hostname: 172.16.10.112
    serviceName: ${spring.application.name}
    healthCheckPath: /actuator/health
    healthCheckInterval: 15s
    tags: urlprefix-/${spring.application.name}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}   
# JWT Config
jwt:
  header: Authorization
  secret: NDU0NTY4amhmc3NkeHp6eGNxdzIlMjFAJTIxQCUyM2ZmNQ==
  expiration: 7200000